name: Build and Release Linux-libicu binary

on:
  push:
    tags:
      - 'v*' 


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        icuversion:
          - 72
          - 74

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build for icu ${{ matrix.icuversion }}
        run: |
          docker build -t icu -f Dockerfile .
          docker run --rm -v ${{ github.workspace }}:/workspace icu /bin/sh -c "cp -v target/release/edit /workspace/edit.icu${{ matrix.icuversion }}"

      - name: Upload asset as artifact 
        uses: actions/upload-artifact@v4
        with:
          name: built-asset-icu${{matrix.icuversion }}
          path: edit.icu${{ matrix.icuversion }}

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: icu artifacts
        uses: actions/download-artifact@v4
#        with:
#          pattern: edit.icu*
#          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release/*
          files: ./*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

